# Config file for automatic testing at travis-ci.org
dist: xenial
language: python
sudo: required

services:
    - docker

matrix:
  include:
    - name: Python 3.6
      python: 3.6
      env: python_version=3.6

    - name: Python 3.7
      python: 3.7
      env: python_version=3.7

    - name: Python 3.8
      python: 3.8
      env: python_version=3.8

  allow_failures:
    - python: 3.8

env:
  global:
    - ES_VERSION=7.3.1
    - PGPORT=5433

cache:
  directories:
    - eggs

install:
  - pip install -U pip
  - pip install -r requirements_dev.txt
  - pip install -e .[test]
  - pip install codecov
  - sleep 1

script:
  - make clean
  - make lint
  - pytest -s --cov=tests -s --tb=native -v --cov-report term-missing --cov-append tests

after_success:
  - codecov
